### ISSUE TITLE
Phrasing constructs (emphasis etc) in dd are rendered on separate lines

### ISSUE THREAD

**Issue by TRIAEIOU** [wataru-chocola/mdast-util-definition-list#60]
Hi,

When converting from mdast to markdown phrasing constructs (such as emphasis etc.) are inserted on separate lines. Stepping through the code this seems to be due to the use of [`containerFlow`](https://github.com/wataru-chocola/mdast-util-definition-list/blob/c9ef2df140850f6509dc26b5d454c3ab10546063/lib/to-markdown.ts#L24) in defListDescriptionHandler rather than containerPhrasing.

[Changing](https://github.com/wataru-chocola/mdast-util-definition-list/blob/c9ef2df140850f6509dc26b5d454c3ab10546063/lib/to-markdown.ts#L23)
```
  const exit = context.enter('defListDescription');
  const value = indentLines(containerFlow(node, context), map);
  exit();
```
[to](https://github.com/wataru-chocola/mdast-util-definition-list/compare/main...TRIAEIOU:mdast-util-definition-list:phrasing-description-handler) (modelled after the defListTermHandler)
```
    const exit = context.enter('defListDescription');
    const subexit = context.enter('phrasing');
    const value = indentLines(containerPhrasing(node, context, { before: '\n', after: '\n'}), map);
    subexit();
    exit();
```
seems to correct the issue but I haven't set up your test environment to see if it has any unwanted side effects. Setting up an example that makes sense requires [this](https://github.com/wataru-chocola/mdast-util-definition-list/issues/59) addition.

**Comment by wataru-chocola** [comment]
Hi @TRIAEIOU, 

Can you tell me what you're trying to do?
If you have HTML text you want to convert into markdown, it would help me.

**Comment by TRIAEIOU** [comment]
Hi,

Yes, I have some HTML that I am converting into markdown.

This (the code also intersects with the other [suggestion](https://github.com/wataru-chocola/mdast-util-definition-list/issues/59) I made)
```
import {defListToMarkdown} from 'mdast-util-definition-list';
import {fromHtml as hastFromHtml} from 'hast-util-from-html';
import {toMarkdown as mdastToMarkdown} from 'mdast-util-to-markdown';
import {toMdast as hastToMdast, all as hastAll} from 'hast-util-to-mdast';
import type {H as HastH} from 'hast-util-to-mdast'
import type {Node as HastNode} from 'hast-util-to-mdast/lib'

const definitionListHastToMdast =
{
    dl: function (h: HastH, node: HastNode) { return h(node, 'defList', hastAll(h, node)); },
    dt: function (h: HastH, node: HastNode) { return h(node, 'defListTerm', hastAll(h, node)); },
    dd: function (h: HastH, node: HastNode) { return h(node, 'defListDescription', hastAll(h, node)); }
}

const html = `<dl><dt>First Term</dt><dd>This is the <strong>definition</strong> of the first term.</dd><dd>This is another definition of the first term.</dd><dt>Second Term</dt><dd>This is one definition of the second term.</dd><dd>This is another definition of the second term.</dd></dl>`;

const hast = hastFromHtml(html);
const mdast = hastToMdast(hast, {
    handlers: {
        ...definitionListHastToMdast
    }    
});
const md = mdastToMarkdown(mdast, {
    extensions: [
        defListToMarkdown
    ]
});
console.log(md);
```
currently results in
```
First Term
:   This is the 

    **definition**

     of the first term.
:   This is another definition of the first term.

Second Term
:   This is one definition of the second term.
:   This is another definition of the second term.
```
whereas I think the expected output would be
```
First Term
:   This is the **definition** of the first term.
:   This is another definition of the first term.

Second Term
:   This is one definition of the second term.
:   This is another definition of the second term.
```
The suggestion in my first post results in the second output (I have not seen any side effects however there may still be some).
