### ISSUE TITLE
How to parse <dl>...</dl> back to markdown

### ISSUE THREAD

**Issue by c-smile** [wataru-chocola/mdast-util-definition-list#80]
Not an issue but rather question...

I have `function md2html(md)`  below that produces `<dl>...</dl>` successfully .
But opposite `function html2md(html)`  does not understand `<dl>...</dl>` as input:
```JavaScript
import { remarkDefinitionList, defListHastHandlers } from 'remark-definition-list';
import { unified } from 'unified';
import remarkGfm from 'remark-gfm';
import remarkParse from 'remark-parse';
import remarkDirective from 'remark-directive';
import remarkRehype from 'remark-rehype';
import remarkStringify from 'remark-stringify';

import rehypeRemark from 'rehype-remark';
import rehypeStringify from 'rehype-stringify';
import rehypeParse from 'rehype-parse';

export async function md2html(md) {
  return unified()
    .use(remarkParse)
    .use(remarkGfm)    
    .use(remarkDirective)
    .use(remarkDefinitionList)
    .use(remarkRehype, {
      handlers: { ...defListHastHandlers }
    })
    .use(rehypeStringify)
    .process(md);
}

export async function html2md(html) {
  return unified()
    .use(rehypeParse)
    .use(rehypeRemark)
    .use(remarkGfm)
    .use(remarkDirective)
    .use(remarkDefinitionList)
    .use(remarkStringify)
    .process(html);
}
```
seems like I need one more piece to this...

**Comment by wataru-chocola** [comment]
Presumably we need [hast-util-to-mdast](https://github.com/syntax-tree/hast-util-to-mdast) extension to convert html to md, as suggested in #59.

I've wanted to make time to create an extension.
Hopefully, I'll try this week.

**Comment by c-smile** [comment]
That would be really great and make DL handling complete in rehype/remark system.

**Comment by wataru-chocola** [comment]
I've just release [hast-util-definition-list], which provides the way to convert hast into mdast.
You can now parse `<dl>` html using this new package like this:

```javascript
import { defListToMarkdown } from "mdast-util-definition-list";
import { fromHtml as hastFromHtml } from "hast-util-from-html";
import { toMarkdown as mdastToMarkdown } from "mdast-util-to-markdown";
import { toMdast as hastToMdast } from "hast-util-to-mdast";
import { defListHastToMdast } from "hast-util-definition-list";

const html = `
<dl>
<dt>First Term</dt>
<dd>This is the <strong>definition</strong> of the first term.</dd>
<dd>This is another definition of the first term.</dd>
<dt>Second Term</dt>
<dd>This is one definition of the second term.</dd>
<dd>This is another definition of the second term.</dd>
</dl>
`;

const hast = hastFromHtml(html, { fragment: true });
const mdast = hastToMdast(hast, {
  handlers: {
    ...defListHastToMdast,
  },
});
const md = mdastToMarkdown(mdast, {
  extensions: [defListToMarkdown],
});
console.log(md);
```

[hast-util-definition-list]: https://www.npmjs.com/package/hast-util-definition-list
[hast-util-to-mdast]: https://github.com/syntax-tree/hast-util-to-mdast

Bad news: you possibly cannot use this together with `rehype-remark` at the moment.

[hast-util-definition-list] depends on the latest version of [hast-util-to-mdast], but `rehype-remark` hasn't upgraded to use it yet as mentioned in [this pr](https://github.com/rehypejs/rehype-remark/pull/15).
As soon as `rehype-remark` upgrade, I'll release a new `remark-definition-list` containing [hast-util-definition-list].

**Comment by wataru-chocola** [comment]
Released.

https://github.com/wataru-chocola/remark-definition-list/releases/tag/v2.0.0
